Build tests image from CI workflow
The metabrainz/musicbrainz-tests image will be built and cached prior to the
two test jobs running. It no longer need to be built and pushed by hand in
advance.

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -9,14 +9,43 @@ on:
       - translations
 
 jobs:
+  build-tests-image:
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v4
+
+      - uses: docker/setup-buildx-action@v3
+
+      - run: |
+          if echo "$GITHUB_BASE_REF-$GITHUB_HEAD_REF" | grep -Pqv '^[\\w-]+$'; then
+            echo 'Invalid branch name'
+            exit 1
+          fi
+          make -C docker config
+
+      - uses: docker/login-action@v3
+        with:
+          username: ${{ secrets.DOCKER_HUB_USERNAME }}
+          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
+
+      - uses: docker/build-push-action@v6
+        with:
+          context: .
+          file: docker/Dockerfile.tests
+          tags: metabrainz/musicbrainz-tests:${{ github.event_name == 'pull_request' && format('{0}-{1}', github.base_ref, github.head_ref) || github.ref_name }}
+          cache-from: type=gha
+          cache-to: type=gha,mode=max
+          push: true
+
   js-perl-and-pgtap:
+    needs: build-tests-image
     runs-on: ubuntu-latest
     env:
       TERM: ansi
       MBS_ROOT: /home/musicbrainz/musicbrainz-server
       NO_YARN: 1 # disables yarn within compile_resources.sh
     container:
-      image: metabrainz/musicbrainz-tests:v-2024-10-30
+      image: metabrainz/musicbrainz-tests:${{ github.event_name == 'pull_request' && format('{0}-{1}', github.base_ref, github.head_ref) || github.ref_name }}
       options: --user root
 
     steps:
@@ -35,13 +64,14 @@ jobs:
           require_tests: true
 
   selenium:
+    needs: build-tests-image
     runs-on: ubuntu-latest
     env:
       TERM: ansi
       MBS_ROOT: /home/musicbrainz/musicbrainz-server
       NO_YARN: 1
     container:
-      image: metabrainz/musicbrainz-tests:v-2024-10-30
+      image: metabrainz/musicbrainz-tests:${{ github.event_name == 'pull_request' && format('{0}-{1}', github.base_ref, github.head_ref) || github.ref_name }}
       options: --user root
 
     steps:
